
services:
  promocode:
    image: ${DOCKER_REGISTRY-}pcfgivingtocustomerwebhost
    build:
      context: .
      dockerfile: Pcf.GivingToCustomer/Pcf.GivingToCustomer.WebHost/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_DBBASE=db_promocode
    depends_on:
    - mongoDbPromoCode  
  mongoDbPromoCode:
    image: mongo:latest
    environment:
      MONGO_DB: db_promocode
    ports:
      - "27044:27017"
    volumes:
      - mongo_data:/var/lib/mongo/data
volumes:
  mongo_data:
